### ISSUE TITLE
Authentication problem

### ISSUE THREAD

**Issue by arikazukito** [rappasoft/laravel-5-boilerplate#847] opened 2017-09-24 02:04 UTC
I have setup this many project using boilerplate.
but in some project:
In local system authentication is smoothly running without any problem but while uploading same file to server and if we try to login it always redirect to login page. can you tell me why is this happening?
i am very much thinking about it

**Comment by brentkozjak** [comment] 2017-09-24 21:02
I would check folder permissions for storage and cache.  Laravel might be trying to write session data and failing with permission denied.  If you're using linux, something like this should do it (executed from your laravel directory):

```
sudo chgrp -R www-data storage bootstrap/cache
sudo chmod -R ug+rwx storage bootstrap/cache
```

**Comment by arikazukito** [comment] 2017-09-25 00:21
It doesnot solve my problem sir

**Comment by bloggervista** [comment] 2017-09-26 07:30
can you clear and check laravel logs and say if any errors occur there?

**Comment by arikazukito** [comment] 2017-09-29 13:12
There is no any error msg in log and in cpanel error log.
Can you visit this site and try to login with any email and password???
Profile1.freewingsofficial.com

**Comment by bloggervista** [comment] 2017-09-29 13:35
Have you seeded the database?
You are using hosting which may impose several risk like if you use sqlite somebody can grab your database. Like your readme.md contains sona etc..

Try VPS hosting they are very cheap 5$ a month if you have any problem you can contact us.

**Comment by arikazukito** [comment] 2017-09-29 22:02
i have seeded database

**Comment by arikazukito** [comment] 2017-09-30 03:10
extensions::uncaught_exception_handler:8Error in event handler for
(unknown): TypeError: anchorBase.attachShadow is not a function
error shows in console in chrome browser

**Comment by arikazukito** [comment] 2017-09-30 03:21
if i try to access
http://profile1.hamronote.com/business
then it shows problem saying trying to get non objet but there is data in
database

**Comment by bloggervista** [comment] 2017-09-30 03:35
show us the line where error occured.

View: /home/hamronote/public_html/Profile1/resources/views/frontend/businessman/index.blade.php

And also show us  63ec82b1bc4bd5a552a145069ab0ec3b68aeb156.php (line 202) show 4-5 lines near that line 202. This file is found in storage view chache folder.

**Comment by arikazukito** [comment] 2017-09-30 04:30
line 487:
    <li><i class="ion-ios-email-outline"></i>Email: <a href="mailto:
example@gmail.com"><?php echo e(Auth::User()->email); ?></a></li>

**Comment by arikazukito** [comment] 2017-09-30 04:42
is there another factor which is causing problem in authentication sir?

**Comment by bloggervista** [comment] 2017-09-30 04:55
i guess it should be Auth::user() by the way . 
And for this to work you must be logged in. If there is logged out user it will throw some form of error. So use Auth::check() first to check if user is logged in or not

**Comment by arikazukito** [comment] 2017-09-30 04:58
what might be other factor which is causing problem in authentication sir?
in local authentiation works fine ..
 in server only it is causing problem ..
hamronote.com is too using boilerplate and there authentication is working
fine ..


On Sat, Sep 30, 2017 at 10:40 AM, Shirshak Bajgain <notifications@github.com

**Comment by bloggervista** [comment] 2017-09-30 05:19
@arikazukito  

en: You are trying to access email but Auth::user() which is null and inderectly you are calling ->email on it. 
For best possible turn on debugging mode etc.. And I cannot explicitly say what might be other factor

np: Aba bro lai nepali aucha jasto cha. Project private huna sakcha tei vayera code dina namileko hola. Pahila kura jastai bro logged in hununna vaney laravel ko Auth Facade lai kei idea hudaina ki kasari email nikalney vanera . Tei vayera bro lay null bata email derive garna khojeko vayera testo error ako ho. Aba tyo code bro lay haleko ho ki hoina vanney kura aucha. Yo boiler plate ma testo code ta hunu naparney ho add garerai hola . Local authentication logged in vayera huna sakcha naako. Logged in huda ki Auth::user() lay App\Model\User ko instance dincha.

Hope it clears.

**Comment by arikazukito** [comment] 2017-09-30 06:38
@bloggervista   i have removed auth::user() in frontend page, thats not issue,
the issue is when i try to login it cause problem, it always redirect to login form page

**Comment by bloggervista** [comment] 2017-09-30 07:40
At Auth Login Controller where have you set redirect url? 
And that redirect url must have some associated routes. 
After that routes there must be some view containing this:
<meta http-equiv="refresh" content="1;url=http://profile1.freewingsofficial.com/login" />

You can search it from text editor.

**Comment by arikazukito** [comment] 2017-10-03 03:00
In local authentication works fine, but when i migrate it in server it shows problem ...

**Comment by bloggervista** [comment] 2017-10-03 03:08
in production try to run with debug mode true.   and many things get turned on and off on production mode. Like ssl is turned on. And check the middleware for redirection located at App\Http\Middleware

**Comment by Shuyinsama** [comment] 2017-10-13 15:43
Any development on this? Is there something we can further help with ?

**Comment by bloggervista** [comment] 2017-10-14 07:05
I guess its fixed.

**Comment by arikazukito** [comment] 2017-10-15 07:08
no it's not fixed, i have put it in another boilerplate repository from
first and then it is fixed

On Sat, Oct 14, 2017 at 12:50 PM, Shirshak Bajgain <notifications@github.com

**Comment by bloggervista** [comment] 2017-10-15 07:13
is it fixed now?

**Comment by bloggervista** [comment] 2017-10-25 02:52
@Shuyinsama  I guess we can close it as laravel 5.4 support is going to  be over. And completely new and fresh version of this boilerplate is to be released soon.

**Comment by triswan** [comment] 2017-10-28 22:51
I have the same problem.. Please don't close it yet, i need the authentication to work very soon to show to my client..
The problem is i cant see any error log while debug mode is on, debugbar is active

**Comment by bloggervista** [comment] 2017-10-29 02:50
@triswan  Try `php artisan config:cache` and check the sessions which is written in file. And please describe how to recreate this issue. Anyway new version of this is coming so i guess you will use that instead of this. Because many component will be replace by package so you will need to upgrade it.

**Comment by triswan** [comment] 2017-11-01 03:32
found the problem, the server could not set cookie, it is not the boilerplate problem...

**Comment by bloggervista** [comment] 2017-11-01 11:05
yes exactly give permissions to those folders.

**Comment by Shuyinsama** [comment] 2017-11-09 12:00
Do you still need any help @arikazukito ? Since there is no way for me to check what might be the problem we can't really help.

You are being redirected to the login page after logging in right?
What is the server setup? (PHP version, Ubuntu version etc etc)

Or did you solve the problem already?

**Closed** 2017-11-16 18:33 UTC
