### ISSUE TITLE
 throw new NotFoundHttpException;

### ISSUE THREAD

**Issue by mikimaine** [rappasoft/laravel-5-boilerplate#429] opened 2016-07-21 10:54 UTC
In the users page it sometimes throw 
` throw new NotFoundHttpException; `

and it will show no users? please help! the previous version doesn't do this things!

**Comment by mikimaine** [comment] 2016-07-22 07:24
![capture](https://cloud.githubusercontent.com/assets/10907808/17049523/7737cf4e-4ff6-11e6-8727-54b8a28c46b9.PNG)

**Comment by mikimaine** [comment] 2016-07-22 09:17
![asd](https://cloud.githubusercontent.com/assets/10907808/17052458/3579999c-5006-11e6-950f-6689c5b69dd0.PNG)

**Comment by rappasoft** [comment] 2016-07-31 17:41
Closing because duplicate of: https://github.com/rappasoft/laravel-5-boilerplate/issues/441

**Closed by rappasoft** 2016-07-31 17:41 UTC
