### ISSUE TITLE
404 on some map files

### ISSUE THREAD

**Issue by petergit67** [rappasoft/laravel-5-boilerplate#221] opened 2016-01-06 14:47 UTC
Hi guys,

Maybe not an valid issue but i get:
![skarmavbild 2016-01-06 kl 15 45 48](https://cloud.githubusercontent.com/assets/6569136/12145137/b23346d8-b48c-11e5-9e44-f4c8b32b6997.png)

**Comment by blomdahldaniel** [comment] 2016-01-06 18:25
What browser are you using? Because I hade the same result when I tried IE a while back. Don't know why.

**Comment by petergit67** [comment] 2016-01-06 18:30
Safari Version 9.0.2 (10601.3.9)

**Comment by blomdahldaniel** [comment] 2016-01-07 00:09
Must have been in Safari I had seen it before. I do not get any error thrown in Chrome dev tools. Any how, I get the same error for some of my projects and some does not throw that error. I will try to investigate if I can see any reasons.

**Comment by blomdahldaniel** [comment] 2016-01-07 00:38
#### debugbar/assets/jquery.min.js.map
The message from debugbar is because of the jquery asset for debugbar.
The error caused by debugbar can be fixed in this file:
`/vendor/maximebf/debugbar/src/DebugBar/Resources/vendor/jquery/dist/jquery.min.js`
at the last row (row nr 6), remove the following line:
```
//# sourceMappingURL=jquery.min.map
```
This will of course come back if the guys at debugbar wont fix this wich I am not sure to why they would bother.

#### app.css.map
The error caused by app.css should be fixed if you just run
`gulp` in your terminal. You might have to run gulp --production (so that the app.css is recompiled). Then you will have a nice and clean debugger again. :)

#### toastr.js.map
I think this was solved for me with gulp --production again. I am not sure this will go away without it thoug..
Otherwise there could be a similar story to this like in the first error for debuger.

**Comment by rappasoft** [comment] 2016-01-07 04:07
I'm not getting any of these errors.

**Comment by blomdahldaniel** [comment] 2016-01-07 09:30
I got them with a new project if I had not run gulp after installation.

**Comment by rappasoft** [comment] 2016-01-08 01:47
Ah because I believe they are gitignored now, so if you run without recompiling gulp you'll get the error, but after you do it's fine. I assume people will gulp at least once before going to production so I don't foresee an issue.

**Comment by blomdahldaniel** [comment] 2016-01-08 01:50
Aah I see. That explains a whole lot. No, it should never be a big issue.

**Closed** 2016-01-08 02:11 UTC
